### ISSUE TITLE
build directory - ui-bundle.zip - automation process in docs

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-ui#6]
Currently the ``build`` directory is excluded by 
```
cat .gitignore
/build/
/node_modules/
/public/

```
If we want to automate the inclusion of ``ui-bundle.zip`` in docs originated in this repro in directory build, we would need to include it.

If I get that right, it would then need on the docs side in site.yml the inclusion (just as an example):
```
ui:
  bundle:
    url: https://github.com/owncloud/docs-ui/build/ui-bundle.zip
    snapshot: true
```
Is that correct?

@tboerger @settermjd
